POST http://localhost:3000/register/
Content-Type: application/json

{
    "userId": 64,
    "userName" : "sureka11",
    "password": "sureka11",
    "age" : 22,
    "location": "kkd",
    "emailId": "ljgh23556",
    "phoneNumber": 987458
  
}
###
POST http://localhost:3000/login/
Content-Type: application/json 

{
    "phoneNumber": 9874582411,
    "password": "sureka11"
}
###

GET http://localhost:3000/gamesList/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NDU4MjQxMSwiaWF0IjoxNjIyMzc2MDA2fQ.QG5QXeCmBhHIlUkHAiW162ze7hY5LK3L_P-S6HH6jfQ
###

GET http://localhost:3000/game/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NDU4MjQxMSwiaWF0IjoxNjIyMzc2MDA2fQ.QG5QXeCmBhHIlUkHAiW162ze7hY5LK3L_P-S6HH6jfQ
###
GET http://localhost:3000/aggregateScore/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6OTg3NDU4MjQxMSwiaWF0IjoxNjIyMzc2MDA2fQ.QG5QXeCmBhHIlUkHAiW162ze7hY5LK3L_P-S6HH6jfQ

